[Config]
internal_timestamp = 10
management_address = "192.168.0.4"
management_port = 9090
polling_interval = 50
control_channel_timeout = 15
data_channel_timeout = 15
file_transfer_timeout = 15
confidence_threshold = 0.5