[Config]
internal_timestamp = 10 # milliseconds
management_address = "192.168.4.2" # IP address
management_port = 9090 # port
refresh_interval = 5 # seconds
polling_interval = 50 # milliseconds
control_channel_timeout = 15 # seconds
data_channel_timeout = 15 # seconds
file_transfer_timeout = 15 # seconds