[Config]
internal_timestamp = 10
agent_listen_port = 9090
http_server_bind_port = 8080
bind_retry_duration = 30
agent_idle_duration = 5
polling_interval = 50
control_channel_timeout = 15
data_channel_timeout = 15
file_transfer_timeout = 15
dedicated_port_range = [60000, 65535]
font_path = "./font.ttf"
border_width = 2
font_size = 15
border_color = [255, 0, 0, 255]
text_color = [0, 0, 255, 255]