[Config]
internal_timestamp = 50
agent_listen_port = 9090
http_server_bind_port = 8080
bind_retry_duration = 30
agent_idle_duration = 5
polling_interval = 100
control_channel_timeout = 10
data_channel_timeout = 10
file_transfer_timeout = 5
dedicated_port_range = [60000, 65535]
font_path = "./font.tff"
border_width = 5
font_size = 40
border_color = [255, 0, 0, 255]
text_color = [0, 0, 255, 255]