[package]
name = "library"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zip = "0.6.6"
toml = "0.8.8"
image = "0.24.8"
rusttype = "0.9.3"
chrono = "0.4.31"
futures = "0.3.30"
actix-rt = "2.9.0"
actix-web = "4.4.1"
imageproc = "0.23.0"
gstreamer = "0.21.3"
rust-embed = "8.2.0"
actix-files = "0.6.1"
lazy_static = "1.4.0"
serde_json = "1.0.111"
actix-multipart = "0.6.1"
sanitize-filename = "0.5.0"
gstreamer-pbutils = "0.21.3"
tokio = { version = "1.35.1", features = ["full"] }
serde = { version = "1.0.195", features = ["derive"] }

[dependencies.uuid]
version = "1.6.1"
features = ["v4", "fast-rng", "macro-diagnostics", "serde"]