[package]
name = "AgentLibrary"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
toml = "0.8.12"
image = "0.24.9"
common = "0.1.0"
chrono = "0.4.35"
sysinfo = "0.30.7"
lazy_static = "1.4.0"
serde_json = "1.0.114"
Common = { path = "../Common" }
tokio = { version = "1.36.0", features = ["full"] }
serde = { version = "1.0.197", features = ["derive"] }
