pub mod agent_information;
pub mod bounding_box;
pub mod confirm_type;
pub mod file_header;
pub mod file_transfer_result;
pub mod inference_type;
pub mod performance;
pub mod task_info;
pub mod task_result;
