[package]
name = "Agent"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
AgentLibrary = { path = "../AgentLibrary" }
tokio = { version = "1.37.0", features = ["rt", "rt-multi-thread", "macros"] }
